### ISSUE TITLE
How to refresh sourceLatLng and destinationLatLng ?

### ISSUE THREAD

**Issue by davamp** [rithik-dev/google_maps_widget#11]

**Comment by rithik-dev** [comment]
Hey, right now the params are set when the widget is initialized, so. Currently, you can pass a ValueKey with the source and destination, and that would cause a rebuild of the widget..

I am working on fix for this issue.

**Comment by rithik-dev** [comment]
Hey @davamp ,  the fix for this is live. Try using version 1.0.5...

You can create a controller, and call methods `setSourceLatLng` or `setDestinationLatLng` to update lat lng.

I've updated the README, go through it, and let me know if you face any issue.

Closing this PR now, and feel free to re-open this issue or create a new one if needed..

Thanks for reporting this issue.
