### ISSUE TITLE
Why another `apiKey` inside the flutter app?

### ISSUE THREAD

**Issue by stephane-segning** [rithik-dev/google_maps_widget#9]
Hello,

thank for this awesome plugin. It simplified my workflow and made me gain some time. Now I just don't understand why I need to add a key inside the dart code, when I already added it inside the android manifest and iOS Runner App, and also the web?

**Comment by rithik-dev** [comment]
Hey @stephane-segning, the key is required for the Directions API. API key is required to be passed to the widget because it relays on web API key which is different than the platform API key.

If you want to use the same API key as from the android manifest, you can try using android_metadata to get the API key from the AndroidManifest.xml at runtime.

Not sure, how this'll work on ios, but a similar approach should work!

**Comment by stephane-segning** [comment]
Agree. But when I looked in detail, the ApiKey isn't used inside the plugin, so I was curious about it

**Comment by rithik-dev** [comment]
It's being used in the Directions class. @stephane-segning 

Here: https://github.com/rithik-dev/google_maps_widget/blob/master/lib/src/models/direction.dart#L45
